export { Posts } from './components/Posts'
export { postsReducer } from './store/postsSlice'
export { postsService } from './services/postsService'
export { useGetSelfPostsProfileQuery } from './services/postsService'
export { useLazyGetSelfPostsProfileQuery } from './services/postsService'
